# Site settings
title: Chill Club
email: Meth@Chill.com
description: Cocaine
baseurl: "/Chill-Club-Page/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: master
github_username: commander

# Build settings
markdown: kramdown
